In [1]:
import pandas as pd
import numpy as np

In [2]:
dataset=pd.read_csv("Placement.csv")

In [3]:
from Univariate import univariate

In [4]:
quan,qual=univariate.quanQual(dataset)

quan
qual
quan
qual
quan
qual
qual
quan
qual
qual
quan
qual
quan
qual
quan

In [ ]:
quan

In [ ]:
qual

In [5]:
dataset.describe()

,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
count,215.000000,215.000000,215.000000,215.000000,215.000000,215.000000,148.000000
mean,108.000000,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
std,62.209324,10.827205,10.897509,7.358743,13.275956,5.833385,93457.452420
min,1.000000,40.890000,37.000000,50.000000,50.000000,51.210000,200000.000000
25%,54.500000,60.600000,60.900000,61.000000,60.000000,57.945000,240000.000000
50%,108.000000,67.000000,65.000000,66.000000,71.000000,62.000000,265000.000000
75%,161.500000,75.700000,73.000000,72.000000,83.500000,66.255000,300000.000000
max,215.000000,89.400000,97.700000,91.000000,98.000000,77.890000,940000.000000

In [6]:
def univariate(dataset,quan):
    descriptive=pd.DataFrame(index=["mean","median","mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5rule","lesser","greater","min","max"],columns=quan)
    for columnName in quan:
        descriptive[columnName]["mean"]=dataset[columnName].mean()
        descriptive[columnName]["median"]=dataset[columnName].median()
        descriptive[columnName]["mode"]=dataset[columnName].mode()[0]
        descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
        descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
        descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
        descriptive[columnName]["99%"]=np.percentile(dataset[columnName],99)       # 99% salary valu not in describe so using percentile 
        descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]      # in ["max"] column
        descriptive[columnName]["IQR"]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]   #(Q3 percentile - Q1 percentile)
        descriptive[columnName]["1.5rule"]=1.5*descriptive[columnName]["IQR"]  #(1.5 * IQR value)
        descriptive[columnName]["lesser"]=descriptive[columnName]["Q1:25%"]-descriptive[columnName]["1.5rule"]  #(Q1-1.5rule)
        descriptive[columnName]["greater"]=descriptive[columnName]["Q3:75%"]+descriptive[columnName]["1.5rule"] #(Q3+1.5rule)
        descriptive[columnName]["min"]=dataset[columnName].min() # dataset minimum value
        descriptive[columnName]["max"]=dataset[columnName].max() # dataset maxmium value
    return descriptive

In [7]:
univariate(dataset,quan)

/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["mean"]=dataset[columnName].mean()
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["median"]=dataset[columnName].median()
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["mode"]=dataset[columnName].mode()[0]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["99%"]=np.percentile(dataset[columnName],99)       # 99% salary valu not in describe so using percentile
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:11: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]      # in ["max"] column
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:12: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["IQR"]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]   #(Q3 percentile - Q1 percentile)
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:13: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["1.5rule"]=1.5*descriptive[columnName]["IQR"]  #(1.5 * IQR value)
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:14: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["lesser"]=descriptive[columnName]["Q1:25%"]-descriptive[columnName]["1.5rule"]  #(Q1-1.5rule)
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:15: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["greater"]=descriptive[columnName]["Q3:75%"]+descriptive[columnName]["1.5rule"] #(Q3+1.5rule)
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:16: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["min"]=dataset[columnName].min() # dataset minimum value
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:17: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["max"]=dataset[columnName].max() # dataset maxmium value
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:4: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["mean"]=dataset[columnName].mean()
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:5: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["median"]=dataset[columnName].median()
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["mode"]=dataset[columnName].mode()[0]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:7: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:8: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:9: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
/var/folders/pr/z6v4w6ps3634swfd3h94s0hc0000gn/T/ipykernel_3713/2626974415.py:10: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value


,sl_no,ssc_p,hsc_p,degree_p,etest_p,mba_p,salary
mean,108.0,67.303395,66.333163,66.370186,72.100558,62.278186,288655.405405
median,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
mode,1,62.0,63.0,65.0,60.0,56.7,300000.0
Q1:25%,54.5,60.6,60.9,61.0,60.0,57.945,240000.0
Q2:50%,108.0,67.0,65.0,66.0,71.0,62.0,265000.0
Q3:75%,161.5,75.7,73.0,72.0,83.5,66.255,300000.0
99%,212.86,87.0,91.86,83.86,97.0,76.1142,NaN
Q4:100%,215.0,89.4,97.7,91.0,98.0,77.89,940000.0
IQR,107.0,15.1,12.1,11.0,23.5,8.31,60000.0
1.5rule,160.5,22.65,18.15,16.5,35.25,12.465,90000.0
lesser,-106.0,37.95,42.75,44.5,24.75,45.48,150000.0
greater,322.0,98.35,91.15,88.5,118.75,78.72,390000.0
min,1,40.89,37.0,50.0,50.0,51.21,200000.0
max,215,89.4,97.7,91.0,98.0,77.89,940000.0

In [8]:
def outlier_columnN(dataset,quan,descriptive):
    Lesser=[]
    Greater=[]
    for columnName in quan:
        if descriptive[columnName]["lesser"]>descriptive[columnName]["min"]:
            Lesser.append(columnName)
        if descriptive[columnName]["greater"]<descriptive[columnName]["max"]:
            Greater.append(columnName)
    return (Lesser,Greater)

In [9]:
outlier_columnN(dataset,quan,descriptive)

NameError: name 'descriptive' is not defined

In [10]:
Lesser=[]
Greater=[]
for columnName in quan:
    if descriptive[columnName]["min"]<descriptive[columnName]["lesser"]:
        Lesser.append(columnName)
    if descriptive[columnName]["max"]>descriptive[columnName]["greater"]:
        Greater.append(columnName)

NameError: name 'descriptive' is not defined

In [ ]:
Lesser

In [ ]:
Greater

In [ ]:
for columnName in Lesser:
    dataset[columnName][dataset[columnName]<descriptive[columnName]["lesser"]]=descriptive[columnName]["lesser"]
for columnName in Greater:
    dataset[columnName][dataset[columnName]>descriptive[columnName]["greater"]]=descriptive[columnName]["greater"]

In [ ]:
descriptive=pd.DataFrame(index=["mean","median","mode","Q1:25%","Q2:50%","Q3:75%","99%","Q4:100%","IQR","1.5rule","lesser","greater","min","max"],columns=quan)
for columnName in quan:
    descriptive[columnName]["mean"]=dataset[columnName].mean()
    descriptive[columnName]["median"]=dataset[columnName].median()
    descriptive[columnName]["mode"]=dataset[columnName].mode()[0]
    descriptive[columnName]["Q1:25%"]=dataset.describe()[columnName]["25%"]
    descriptive[columnName]["Q2:50%"]=dataset.describe()[columnName]["50%"]
    descriptive[columnName]["Q3:75%"]=dataset.describe()[columnName]["75%"]
    descriptive[columnName]["99%"]=np.percentile(dataset[columnName],99)       # 99% salary valu not in describe so using percentile 
    descriptive[columnName]["Q4:100%"]=dataset.describe()[columnName]["max"]      # in ["max"] column
    descriptive[columnName]["IQR"]=descriptive[columnName]["Q3:75%"]-descriptive[columnName]["Q1:25%"]   #(Q3 percentile - Q1 percentile)
    descriptive[columnName]["1.5rule"]=1.5*descriptive[columnName]["IQR"]  #(1.5 * IQR value)
    descriptive[columnName]["lesser"]=descriptive[columnName]["Q1:25%"]-descriptive[columnName]["1.5rule"]  #(Q1-1.5rule)
    descriptive[columnName]["greater"]=descriptive[columnName]["Q3:75%"]+descriptive[columnName]["1.5rule"] #(Q3+1.5rule)
    descriptive[columnName]["min"]=dataset[columnName].min() # dataset minimum value
    descriptive[columnName]["max"]=dataset[columnName].max() # dataset maxmium value

In [ ]:
descriptive

In [ ]:
replace_Lesser=[]
replace_Greater=[]
for columnName in quan:
    if descriptive[columnName]["min"]<descriptive[columnName]["lesser"]:
        replace_Lesser.append(columnName)
    if descriptive[columnName]["greater"]<descriptive[columnName]["max"]:
        replace_Greater.append(columnName)

In [ ]:
replace_Lesser

In [ ]:
replace_Greater

# Frequency(reputed unick value count)

In [ ]:
dataset["ssc_p"].value_counts() # unique values and no.of repetated value(frequency)

In [ ]:
dataset["ssc_p"].value_counts().index  #only show an index(unique values)

In [ ]:
dataset["ssc_p"].value_counts().values  #only show an frequency value(reputation) count values

In [ ]:
dataset["ssc_p"].value_counts().sort_values # unick values with decending order (B to S)

In [ ]:
dataset["ssc_p"].value_counts().sort_index  #decending order for frequency count values

In [ ]:
def freqTable(columnName,dataset):
    freqTable=pd.DataFrame(columns=["Unique_values","Frequency","Relative_Frequency","cumsum"])
    freqTable["Unique_values"]=dataset[columnName].value_counts().index
    freqTable["Frequency"]=dataset[columnName].value_counts().values
    freqTable["Relative_Frequency"]=(freqTable["Frequency"]/103)
    freqTable["cumsum"]=freqTable["Relative_Frequency"].cumsum()
    return freqTable

In [ ]:
freqTable("ssc_p",dataset) # calling the freqTable funtion